language: node_js
node_js:
- '8'
script:
- ng build -prod
before_deploy:
- tar -czf wxdisplay-$TRAVIS_BRANCH.tar.gz -C dist .
deploy:
- provider: releases
  api_key:
    secure: gjrUQTRTNedhAmQ0XaWQfAJiPO7XqrCitdXeDQXuWpix4ucDlrzFOsyRLqck19XjWBQKZ5FI4NowOYUA9ntvV5TcrU9SvLaf3fR9CteEgbSt6r3U9nVIrn5PKnmKbeFfwYThfUQt6aQZ94NBaavDVcm89rzsqnwLo7YsQB5T+gh2AwFKJAJzVA54i05UAsGSAY8dYERsGDjNY1wQ+wMsNyg/4nzZPcOygIxdbRFCLv710CIFeHHi2YVXd5N4ir12xD0kDu6pkPCQVarJ3hDn+PAGMcN5D2YKjHkgzFd9ID9vw2QxE1vbMz4RczFvmHVweO1ML099gNOhWLz3jMtxKZO/WJixxVmSfjnJsaNsB/XGV382m8E8rbl22kKcfg5hraRF3sxA1RHo8D7ZKXDPpzQn3kR8qHPwgi1d4z2h1omIxs0A0wRvqCpmThe39+Kcckq8IJy/6CeoHPuj9W+iJtcGo04E3/tk89THfJnsPQrb41M0YRzWFMLD8emzE+O4EV15EfdZsOH56xC7Xqo4yB6l6FyLu7HBJalMPrRIUZGyAbnKBwkZvGvWlLuVFn1wK1sSsjy5gQnMHmchlBDIC4pS42fRs+GRavhNJOARyCUcHYUIboPFcAOl4jTQQgjnGJ76naH+NEQFBzogFcTn0rbTWYqVH4SWlF7yylm1lhY=
  file: wxdisplay-$TRAVIS_BRANCH.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  github_token:
    secure: gjrUQTRTNedhAmQ0XaWQfAJiPO7XqrCitdXeDQXuWpix4ucDlrzFOsyRLqck19XjWBQKZ5FI4NowOYUA9ntvV5TcrU9SvLaf3fR9CteEgbSt6r3U9nVIrn5PKnmKbeFfwYThfUQt6aQZ94NBaavDVcm89rzsqnwLo7YsQB5T+gh2AwFKJAJzVA54i05UAsGSAY8dYERsGDjNY1wQ+wMsNyg/4nzZPcOygIxdbRFCLv710CIFeHHi2YVXd5N4ir12xD0kDu6pkPCQVarJ3hDn+PAGMcN5D2YKjHkgzFd9ID9vw2QxE1vbMz4RczFvmHVweO1ML099gNOhWLz3jMtxKZO/WJixxVmSfjnJsaNsB/XGV382m8E8rbl22kKcfg5hraRF3sxA1RHo8D7ZKXDPpzQn3kR8qHPwgi1d4z2h1omIxs0A0wRvqCpmThe39+Kcckq8IJy/6CeoHPuj9W+iJtcGo04E3/tk89THfJnsPQrb41M0YRzWFMLD8emzE+O4EV15EfdZsOH56xC7Xqo4yB6l6FyLu7HBJalMPrRIUZGyAbnKBwkZvGvWlLuVFn1wK1sSsjy5gQnMHmchlBDIC4pS42fRs+GRavhNJOARyCUcHYUIboPFcAOl4jTQQgjnGJ76naH+NEQFBzogFcTn0rbTWYqVH4SWlF7yylm1lhY=
  skip_cleanup: true
  local_dir: dist
  fqdn: knightdale.pabstfam.com
  on:
    tags: true